#!/usr/bin/bash
# This file acts as an input file for build_sfvmk_pkg.sh
# Devs must change the release/debug tags as per build cycle
# User can comment out any ESX version that are not needed
# Other than ESXi version, nothing else needs a change
# unless the nDDK_VMs are changed.
# Warning: file not self executable, won't yield anything
#***********************************************************

# ESXi information array
# to be filled as: "<ESX_VER>;<NDDK_PATH>;<VM_IP>;<sfvmkcli_build>"
# Note: ESXCLI is built only for 6.0 and the same VIB works for higher versions of ESXi
ESX[0]="6.0;/opt/vmware/nativeddk-6.0.0-2768847/src;10.40.128.99;cli"
ESX[1]="6.5;/opt/vmware/nativeddk-6.5.0-4598673/src;10.40.128.87;no"
ESX[2]="6.7;/opt/vmware/nativeddk-6.7.0-8169922/src;10.40.128.67;no"

# TAG information array
# to be filled as: "<tag>;<rel/debug>;<yes/no[for src package>]"
# Release tag
TAGS[0]="v2.3.3.1000;rel;yes"
# Debug tag
TAGS[1]="v2.3.3.1001;debug;no"
#firmware family tag
FW_FAMILY="v7.7.0.1003"
#Use any one manifest_list file:-
#dell_manifest_list
#fw_manifest_list
#sixpence_manifest_list
#sol_manifest_list
MANIFEST_LIST="dell_manifest_list"
#firmware vib build VM
VIB_TOOL[0]="6.5;/opt/vmware/nativeddk-6.5.0-4598673/src;10.40.128.87;yes"
VIB_TOOL[1]="6.7;/opt/vmware/hexdk-6.7.0-8169922/;10.40.128.67;no"
#export all esx versions in form of array
export ESX
#export all tags in form of array
export TAGS

