CP           = /build/toolchain/lin32/coreutils-6.9/bin/cp
MKDIR        = /build/toolchain/lin32/coreutils-6.9/bin/mkdir
MV           = /build/toolchain/lin32/coreutils-6.9/bin/mv
RM           = /build/toolchain/lin32/coreutils-6.9/bin/rm
AWK          = /build/toolchain/lin32/gawk-3.1.5/bin/awk
GREP         = /build/toolchain/lin32/grep-2.5.1a/bin/grep
MAKE         = /build/toolchain/lin32/make-3.81/bin/make
SED          = /build/toolchain/lin32/sed-4.1.5/bin/sed

